namespace: purestorage
name: blade
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  purestorage.common: '>=1.0'
repository: git@github.com:coll-test/purestorage.blade.git
documentation: https://github.com/coll-test/purestorage.blade/tree/master/docs
homepage: https://github.com/coll-test/purestorage.blade
issues: https://github.com/coll-test/purestorage.blade/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
